Feature/#
uzumal/openlab pull request #14
Opened 2021-05-16 11:16 UTC by uzumal

2021-05-16 11:28 UTC, tayoon requested changes
え、これopenlabの更新で合ってる？
Hikaru Nakataって書いてあるけど…
修正よろです

2021-05-16 12:54 UTC, uzumal commented
とりあえずこれでよろしく〜
まだmainへのマージは無しでおけ

2021-05-16 13:33 UTC, tayoon commented
@uzumal 
mainへのプルリクになってるで笑

2021-05-16 13:52 UTC, uzumal commented
> @uzumal
> mainへのプルリクになってるで笑

あっれ〜（笑）まあマージ良きです！

2021-05-17 02:13 UTC, tayoon commented
このプルリク、クローズして、developへのプルリクをしてくれん？ちょっとややこしいから…
すまんやで

2021-05-17 02:32 UTC, closed without merging